Add a test (fails on Debug) for #9790 and add missing include in PipeHeatTransfer.hh
```
[ RUN      ] EnergyPlusFixture.CalcPipeHeatTransCoef
/usr/include/c++/10/debug/array:68:
In function:
    std::__debug::array<_Tp, 
    _Nm>::_Array_check_subscript<_Size>::_Array_check_subscript(std::size_t) 
    [with long unsigned int _Size = 13; _Tp = double; long unsigned int _Nm 
    = 13; std::size_t = long unsigned int]

Error: attempt to subscript container with out-of-bounds index -1, but 
container only holds 13 elements.

Objects involved in the operation:
    sequence "this" @ 0x0x55dca7207f50 {
      type = std::__debug::array<double, 13ul>::_Array_check_subscript<13ul>;
    }
Aborted (core dumped)
```