Catch the case where you forgot to add a semicolon at the end of an object
```
[  4%][1/21] Generating ../Products/Energy+.schema.epJSON
FAILED: Products/Energy+.schema.epJSON /home/julien/Software/Others/EnergyPlus-build-release2/Products/Energy+.schema.epJSON 
cd /home/julien/Software/Others/EnergyPlus-build-release2/idd && /home/julien/.pyenv/versions/3.8.13/bin/python3.8 /home/julien/Software/Others/EnergyPlus2/idd/schema/generate_epJSON_schema.py /home/julien/Software/Others/EnergyPlus-build-release2/Products
Generating the epJSON schema!
Process Process-1:
Traceback (most recent call last):
  File "/home/julien/.pyenv/versions/3.8.13/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/julien/.pyenv/versions/3.8.13/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/julien/Software/Others/EnergyPlus2/idd/schema/generate_epJSON_schema.py", line 84, in generate_epJSON_schema
    idd_parser.parse_idd(data)
  File "/home/julien/Software/Others/EnergyPlus2/idd/schema/idd_parser.py", line 217, in parse_idd
    obj_data = parse_obj(data, obj_name=obj_name)
  File "/home/julien/Software/Others/EnergyPlus2/idd/schema/idd_parser.py", line 444, in parse_obj
    raise MissingSemiColonException(
idd_parser.MissingSemiColonException: In object 'SimulationControl', Missing semi-colon in field N1
Context:
      \note Currently limited to use with coincident plant sizing, see Sizing:Plant object
      \type choice
      \key Yes
      \key No
      \default No
  N1, \field Maximum Number of HVAC Sizing Simulation Passes
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      \note the entire set of SizingPeriod:* objects may be repeated to fine tune size results
      \note this input sets a limit on the number of passes that the sizing algorithms can repeate the set
      \type integer
      \minimum 1
ninja: build stopped: subcommand failed.
```